"""docs/cli-reference.md must match what build_parser() prints.

The reference is generated by tools/gen_cli_reference.py. This module fails
when the committed file drifts from the parser, when a documented verb is not
shipped, or when a hidden verb leaks into the reference.
"""
from __future__ import annotations

import argparse
import importlib.util
import os
import re
import subprocess
import sys
from pathlib import Path

import pytest

from conftest import child_env


REPO = Path(__file__).resolve().parents[1]
GENERATOR = REPO / "tools" / "gen_cli_reference.py"
REFERENCE = REPO / "docs" / "cli-reference.md"


def _load_generator():
    spec = importlib.util.spec_from_file_location("gen_cli_reference", GENERATOR)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


gen = _load_generator()
fleet = gen.load_fleet(REPO)


def _shipped_visible_verbs() -> set[str]:
    parser = fleet.build_parser()
    for action in parser._actions:
        if isinstance(action, argparse._SubParsersAction):
            return {choice.dest for choice in action._choices_actions
                    if choice.help != argparse.SUPPRESS}
    raise AssertionError("parser has no subcommands")


def _shipped_all_verbs() -> set[str]:
    parser = fleet.build_parser()
    for action in parser._actions:
        if isinstance(action, argparse._SubParsersAction):
            return set(action.choices)
    raise AssertionError("parser has no subcommands")


def _commands(parser, prefix=(), *, visible_only: bool) -> dict[str, argparse.ArgumentParser]:
    for action in parser._actions:
        if not isinstance(action, argparse._SubParsersAction):
            continue
        summaries = {choice.dest: choice.help for choice in action._choices_actions}
        commands = {}
        for name, subparser in action.choices.items():
            if visible_only and summaries.get(name) == argparse.SUPPRESS:
                continue
            path = (*prefix, name)
            commands[" ".join(path)] = subparser
            commands.update(_commands(
                subparser, path, visible_only=visible_only))
        return commands
    return {}


def _shipped_visible_commands() -> dict[str, argparse.ArgumentParser]:
    return _commands(fleet.build_parser(), visible_only=True)


def _shipped_all_commands() -> dict[str, argparse.ArgumentParser]:
    return _commands(fleet.build_parser(), visible_only=False)


def test_committed_reference_matches_the_parser():
    rendered = gen.render(fleet)
    committed = REFERENCE.read_text(encoding="utf-8")
    assert committed == rendered, (
        "docs/cli-reference.md has drifted from build_parser(). Regenerate "
        "with: python tools/gen_cli_reference.py")


def test_generator_check_mode_agrees_with_the_test():
    result = subprocess.run(
        [sys.executable, str(GENERATOR), "--check"], cwd=REPO,
        capture_output=True, text=True)
    assert result.returncode == 0, result.stderr


def test_render_does_not_depend_on_terminal_width(monkeypatch):
    monkeypatch.setenv("COLUMNS", "200")
    wide = gen.render(fleet)
    monkeypatch.setenv("COLUMNS", "40")
    narrow = gen.render(fleet)
    assert wide == narrow


def test_render_leaves_the_caller_environment_alone(monkeypatch):
    monkeypatch.setenv("COLUMNS", "123")
    gen.render(fleet)
    assert os.environ["COLUMNS"] == "123"


def test_option_aliases_repeat_their_metavar_in_the_reference():
    rendered = gen.render(fleet)
    expected = (
        "-n LINES, --lines LINES",
        "--since SINCE, --recorded-sha SINCE",
        "--wake-when WAKE_CONDITION, --wake-condition WAKE_CONDITION",
    )
    for invocation in expected:
        assert invocation in rendered, invocation


def test_sup_reconcile_reference_states_action_exclusivity():
    parser = _shipped_visible_commands()["sup-reconcile"]
    groups = parser._mutually_exclusive_groups
    help_text = gen.render(fleet)
    gen._stable_help(parser)
    assert parser._mutually_exclusive_groups is groups
    section = help_text.split("### fleet sup-reconcile\n", 1)[1].split("\n### ", 1)[0]
    assert "Choose at most one reconciliation action." in section
    assert "At most one of `--prepare-recorded-policy-restore` or" in section
    with pytest.raises(SystemExit):
        parser.parse_args([
            "--prepare-recorded-policy-restore",
            "--restore-recorded-policy",
        ])


def test_reference_describes_every_mutually_exclusive_group():
    expected = {
        "homes": "At most one of `--add` or `--retire` may be used.",
        "pr-poll": (
            "Exactly one of `--since` (alias `--recorded-sha`) or "
            "`--since-file` is required."),
        "wait": "At most one of `--any` or `--all` may be used.",
        "codex-decline-fixed": (
            "Exactly one of `--expect-request-cwd` or "
            "`--expect-cwd-absent` is required."),
        "clean": "At most one of `--dead-only` or `--tombstones` may be used.",
    }
    rendered = gen.render(fleet)
    for command, constraint in expected.items():
        section = rendered.split(f"### fleet {command}\n", 1)[1].split(
            "\n### ", 1)[0]
        assert f"Constraint: {constraint}" in " ".join(section.split())


def test_reference_generation_preserves_groups_and_parser_validation():
    for _path, _summary, parser in gen._visible_commands(fleet.build_parser()):
        original = parser._mutually_exclusive_groups
        snapshots = [tuple(group._group_actions) for group in original]
        gen._stable_help(parser)
        assert parser._mutually_exclusive_groups is original
        assert [tuple(group._group_actions) for group in original] == snapshots
        for group in original:
            assert len(group._group_actions) >= 2
            argv = []
            for action in group._group_actions[:2]:
                argv.append(action.option_strings[0])
                if action.nargs != 0:
                    argv.append("value")
            with pytest.raises(SystemExit) as error:
                parser.parse_args(argv)
            assert error.value.code == 2


def _documented_verbs() -> list[str]:
    text = REFERENCE.read_text(encoding="utf-8")
    return re.findall(r"^### fleet (\S+)$", text, flags=re.MULTILINE)


def _documented_commands() -> list[str]:
    text = REFERENCE.read_text(encoding="utf-8")
    return re.findall(r"^#{3,6} fleet (.+)$", text, flags=re.MULTILINE)


def test_every_documented_verb_is_shipped():
    documented = _documented_verbs()
    assert documented, "no verb sections found in docs/cli-reference.md"
    missing = sorted(set(documented) - _shipped_all_verbs())
    assert not missing, f"reference documents verbs the parser lacks: {missing}"


def test_every_visible_verb_has_a_section():
    documented = set(_documented_verbs())
    absent = sorted(_shipped_visible_verbs() - documented)
    assert not absent, f"parser verbs with no reference section: {absent}"


def test_hidden_verbs_are_not_documented():
    hidden = _shipped_all_verbs() - _shipped_visible_verbs()
    assert hidden, "expected at least one hidden verb to pin this behaviour"
    leaked = sorted(hidden & set(_documented_verbs()))
    assert not leaked, f"hidden verbs appear in the reference: {leaked}"


def test_every_visible_nested_command_has_a_section_and_its_options():
    documented = set(_documented_commands())
    shipped = _shipped_visible_commands()
    assert documented == set(shipped)
    expected_nested = {
        "mail verify", "index init", "index build", "index update", "index status"}
    assert expected_nested <= documented
    text = REFERENCE.read_text(encoding="utf-8")
    for command in expected_nested:
        assert shipped[command].format_help().rstrip() in text


def test_no_hidden_nested_command_is_documented():
    hidden = set(_shipped_all_commands()) - set(_shipped_visible_commands())
    leaked = sorted(hidden & set(_documented_commands()))
    assert not leaked, f"hidden commands appear in the reference: {leaked}"


def test_always_refusing_attach_is_hidden_from_actual_help(tmp_path):
    result = subprocess.run(
        [sys.executable, str(REPO / "bin" / "fleet.py"), "--help"],
        cwd=REPO, env=child_env(tmp_path), capture_output=True, text=True)
    assert result.returncode == 0, result.stderr
    choice_list = re.search(
        r"usage: fleet \[-h\]\s+\{([^}]+)\}", result.stdout)
    assert choice_list, result.stdout
    assert "attach" not in choice_list.group(1).split(",")
    assert re.search(r"(?m)^\s+attach(?:\s|$)", result.stdout) is None
    assert "==SUPPRESS==" not in result.stdout


def test_spawn_effort_help_names_legacy_mcx_and_native_ignored():
    text = REFERENCE.read_text(encoding="utf-8")
    flattened = re.sub(r"\s+", " ", text)
    assert (
        "legacy mcx reasoning effort; ignored by the native Codex adapter"
        in flattened)


@pytest.mark.parametrize("command", sorted(_shipped_visible_commands()))
def test_each_command_section_carries_its_own_usage_line(command):
    text = REFERENCE.read_text(encoding="utf-8")
    assert f"usage: fleet {command}" in text


@pytest.mark.parametrize("command", sorted(_shipped_visible_commands()))
def test_actual_nested_help_has_one_usage_prefix(command):
    help_text = _shipped_visible_commands()[command].format_help()
    usage_lines = [line for line in help_text.splitlines()
                   if line.startswith("usage:")]
    assert usage_lines, help_text
    assert usage_lines[0].startswith(f"usage: fleet {command}"), help_text
    assert help_text.count("usage:") == 1, help_text
