"""docs/cli-reference.md must match what build_parser() prints.

The reference is generated by tools/gen_cli_reference.py. This module fails
when the committed file drifts from the parser, when a documented verb is not
shipped, or when a hidden verb leaks into the reference.
"""
from __future__ import annotations

import argparse
import importlib.util
import os
import re
import subprocess
import sys
from pathlib import Path

import pytest


REPO = Path(__file__).resolve().parents[1]
GENERATOR = REPO / "tools" / "gen_cli_reference.py"
REFERENCE = REPO / "docs" / "cli-reference.md"


def _load_generator():
    spec = importlib.util.spec_from_file_location("gen_cli_reference", GENERATOR)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


gen = _load_generator()
fleet = gen.load_fleet(REPO)


def _shipped_visible_verbs() -> set[str]:
    parser = fleet.build_parser()
    for action in parser._actions:
        if isinstance(action, argparse._SubParsersAction):
            return {choice.dest for choice in action._choices_actions
                    if choice.help != argparse.SUPPRESS}
    raise AssertionError("parser has no subcommands")


def _shipped_all_verbs() -> set[str]:
    parser = fleet.build_parser()
    for action in parser._actions:
        if isinstance(action, argparse._SubParsersAction):
            return set(action.choices)
    raise AssertionError("parser has no subcommands")


def _commands(parser, prefix=(), *, visible_only: bool) -> dict[str, argparse.ArgumentParser]:
    for action in parser._actions:
        if not isinstance(action, argparse._SubParsersAction):
            continue
        summaries = {choice.dest: choice.help for choice in action._choices_actions}
        commands = {}
        for name, subparser in action.choices.items():
            if visible_only and summaries.get(name) == argparse.SUPPRESS:
                continue
            path = (*prefix, name)
            commands[" ".join(path)] = subparser
            commands.update(_commands(
                subparser, path, visible_only=visible_only))
        return commands
    return {}


def _shipped_visible_commands() -> dict[str, argparse.ArgumentParser]:
    return _commands(fleet.build_parser(), visible_only=True)


def _shipped_all_commands() -> dict[str, argparse.ArgumentParser]:
    return _commands(fleet.build_parser(), visible_only=False)


def test_committed_reference_matches_the_parser():
    rendered = gen.render(fleet)
    committed = REFERENCE.read_text(encoding="utf-8")
    assert committed == rendered, (
        "docs/cli-reference.md has drifted from build_parser(). Regenerate "
        "with: python tools/gen_cli_reference.py")


def test_generator_check_mode_agrees_with_the_test():
    result = subprocess.run(
        [sys.executable, str(GENERATOR), "--check"], cwd=REPO,
        capture_output=True, text=True)
    assert result.returncode == 0, result.stderr


def test_render_does_not_depend_on_terminal_width(monkeypatch):
    monkeypatch.setenv("COLUMNS", "200")
    wide = gen.render(fleet)
    monkeypatch.setenv("COLUMNS", "40")
    narrow = gen.render(fleet)
    assert wide == narrow


def test_render_leaves_the_caller_environment_alone(monkeypatch):
    monkeypatch.setenv("COLUMNS", "123")
    gen.render(fleet)
    assert os.environ["COLUMNS"] == "123"


def _documented_verbs() -> list[str]:
    text = REFERENCE.read_text(encoding="utf-8")
    return re.findall(r"^### fleet (\S+)$", text, flags=re.MULTILINE)


def _documented_commands() -> list[str]:
    text = REFERENCE.read_text(encoding="utf-8")
    return re.findall(r"^#{3,6} fleet (.+)$", text, flags=re.MULTILINE)


def test_every_documented_verb_is_shipped():
    documented = _documented_verbs()
    assert documented, "no verb sections found in docs/cli-reference.md"
    missing = sorted(set(documented) - _shipped_all_verbs())
    assert not missing, f"reference documents verbs the parser lacks: {missing}"


def test_every_visible_verb_has_a_section():
    documented = set(_documented_verbs())
    absent = sorted(_shipped_visible_verbs() - documented)
    assert not absent, f"parser verbs with no reference section: {absent}"


def test_hidden_verbs_are_not_documented():
    hidden = _shipped_all_verbs() - _shipped_visible_verbs()
    assert hidden, "expected at least one hidden verb to pin this behaviour"
    leaked = sorted(hidden & set(_documented_verbs()))
    assert not leaked, f"hidden verbs appear in the reference: {leaked}"


def test_every_visible_nested_command_has_a_section_and_its_options():
    documented = set(_documented_commands())
    shipped = _shipped_visible_commands()
    assert documented == set(shipped)
    expected_nested = {
        "mail verify", "index init", "index build", "index update", "index status"}
    assert expected_nested <= documented
    text = REFERENCE.read_text(encoding="utf-8")
    for command in expected_nested:
        assert shipped[command].format_help().rstrip() in text


def test_no_hidden_nested_command_is_documented():
    hidden = set(_shipped_all_commands()) - set(_shipped_visible_commands())
    leaked = sorted(hidden & set(_documented_commands()))
    assert not leaked, f"hidden commands appear in the reference: {leaked}"


@pytest.mark.parametrize("command", sorted(_shipped_visible_commands()))
def test_each_command_section_carries_its_own_usage_line(command):
    text = REFERENCE.read_text(encoding="utf-8")
    assert f"usage: fleet {command}" in text
